# Generated by Django 5.1.5 on 2025-01-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
