# Generated by Django 5.1.5 on 2025-01-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.FileField(null=True, upload_to='media/student_image'),
        ),
    ]
