# Generated by Django 5.1.4 on 2025-01-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cat', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=200)),
                ('img', models.FileField(upload_to='media/Event_Image')),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
    ]
