# Generated by Django 5.1.4 on 2025-01-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imp', models.CharField(choices=[('Emergency', 'Emergency'), ('Important', 'Important'), ('General', 'General')], max_length=100)),
                ('message', models.TextField()),
                ('btn_name', models.CharField(blank=True, max_length=100, null=True)),
                ('btn_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
