# Generated by Django 5.1.4 on 2025-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
