# Generated by Django 5.1.4 on 2025-01-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customuser_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='btn_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SemesterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField()),
                ('total_credits', models.CharField(max_length=20)),
                ('pdf_file', models.FileField(upload_to='registration_pdfs/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('internal_mark', models.IntegerField()),
                ('attendance', models.CharField(max_length=20)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.semesterregistration')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('credits_earned', models.CharField(max_length=20)),
                ('sgpa', models.FloatField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.semesterregistration')),
            ],
        ),
    ]
