# Generated by Django 5.1.4 on 2025-01-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_notification_btn_link_semesterregistration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterresult',
            name='registration',
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='year',
            field=models.CharField(default=2025, max_length=100),
        ),
        migrations.DeleteModel(
            name='CourseAttendance',
        ),
        migrations.DeleteModel(
            name='SemesterResult',
        ),
    ]
