# Generated by Django 5.1.4 on 2025-01-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_semesterresult_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterregistration',
            name='notification_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.notification'),
        ),
    ]
