# Generated by Django 5.1.7 on 2025-03-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='registration_pdfs/')),
                ('notification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.notification')),
            ],
        ),
    ]
