# Generated by Django 5.1.4 on 2025-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_semesterregistration_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterregistration',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='semesterregistration',
            name='total_credits',
        ),
        migrations.AlterField(
            model_name='semesterregistration',
            name='year',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
