# Generated by Django 5.1.7 on 2025-03-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_semesterregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='btn_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
