# Generated by Django 5.1.4 on 2025-01-30 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_semesterregistration_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
