# Generated by Django 5.1.4 on 2025-01-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_semesterregistration_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterregistration',
            name='year',
        ),
        migrations.AlterField(
            model_name='semesterregistration',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
