# Generated by Django 5.1.7 on 2025-04-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_notification_btn_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
