# Generated by Django 5.1.4 on 2025-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_semesterregistration_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.FileField(upload_to='Event_Image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.FileField(null=True, upload_to='student_image'),
        ),
    ]
