# Generated by Django 5.1.4 on 2025-01-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_event_img_alter_student_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('desig', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac_new', to='accounts.department')),
            ],
        ),
    ]
